name: ca_imaging
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - asciitree=0.3.3=py_2
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - blosc=1.16.3=h7bd577a_0
  - bokeh=1.4.0=py37_0
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_0
  - click=7.0=py37_0
  - cloudpickle=1.2.2=py_0
  - colorama=0.4.3=py_0
  - cycler=0.10.0=py37_0
  - cytoolz=0.10.1=py37he774522_0
  - dask=2.3.0=py_0
  - dask-core=2.3.0=py_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - distributed=2.5.2=py_0
  - easydict=1.9=py_0
  - entrypoints=0.3=py37_0
  - fasteners=0.15=py_0
  - ffmpeg=4.2=ha925a31_0
  - freetype=2.9.1=ha9979f8_1
  - fsspec=0.6.2=py_0
  - h5py=2.8.0=py37h3bdd7fb_2
  - hdf5=1.10.2=hac2f561_1
  - heapdict=1.0.1=py_0
  - holoviews=1.12.7=py_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha66f8fd_1
  - importlib_metadata=1.5.0=py37_0
  - inflect=4.1.0=py37_0
  - intel-openmp=2019.4=245
  - ipykernel=5.1.4=py37h39e3cac_0
  - ipython=7.12.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - jaraco.itertools=5.0.0=py_0
  - jedi=0.16.0=py37_0
  - jinja2=2.11.1=py_0
  - joblib=0.14.1=py_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=3.2.0=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.3.4=py37_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.1=py37_0
  - kiwisolver=1.1.0=py37ha925a31_0
  - libblas=3.8.0=12_mkl
  - libcblas=3.8.0=12_mkl
  - libopencv=3.4.1=h875b8b8_3
  - libpng=1.6.37=h2a8f88b_0
  - libsodium=1.0.16=h9d3ae62_0
  - libtiff=4.1.0=h56a325e_0
  - locket=0.2.0=py37_1
  - lz4-c=1.8.1.2=h2fa13f4_0
  - lzo=2.10=h6df0209_2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py37he774522_0
  - matplotlib=3.1.1=py37_1
  - matplotlib-base=3.1.1=py37h2852a4a_1
  - mistune=0.8.4=py37he774522_0
  - mkl=2019.4=245
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.0.15=py37h14836fe_0
  - mkl_random=1.1.0=py37h675688f_0
  - monotonic=1.5=py_0
  - more-itertools=8.2.0=py_0
  - moviepy=0.2.3.5=py_0
  - msgpack-python=0.6.1=py37h74a9793_1
  - msys2-conda-epoch=20160418=1
  - natsort=6.0.0=py_0
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.4=py_0
  - notebook=6.0.3=py37_0
  - numcodecs=0.6.4=py37ha925a31_0
  - numexpr=2.7.1=py37h25d0782_0
  - numpy=1.16.4=py37h19fb1c0_0
  - numpy-base=1.16.4=py37hc3f5095_0
  - olefile=0.46=py37_0
  - opencv=3.4.1=py37h6fd60c2_3
  - openssl=1.1.1d=he774522_4
  - packaging=20.1=py_0
  - pandas=1.0.0=py37h47e9c7a_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - param=1.9.3=py_0
  - parso=0.6.0=py_0
  - partd=1.1.0=py_0
  - pickleshare=0.7.5=py37_0
  - pillow=7.0.0=py37hcc1f983_0
  - pip=20.0.2=py37_1
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.3=py_0
  - psutil=5.6.7=py37he774522_0
  - py-opencv=3.4.1=py37h1b0d24d_3
  - pygments=2.5.2=py_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py37h6538335_2
  - pyrsistent=0.15.7=py37he774522_0
  - pyserial=3.4=py37_0
  - pytables=3.4.4=py37he6f6034_0
  - python=3.7.4=h5263a28_0
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pyviz_comms=0.7.3=py_0
  - pywin32=227=py37he774522_1
  - pywinpty=0.5.7=py37_0
  - pyyaml=5.3=py37he774522_0
  - pyzmq=18.1.1=py37ha925a31_0
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=4.6.0=py_1
  - scikit-learn=0.21.3=py37h7208079_0
  - scipy=1.3.1=py37h29ff71c_0
  - send2trash=1.5.0=py37_0
  - setuptools=45.1.0=py37_0
  - sip=4.19.8=py37h6538335_0
  - six=1.14.0=py37_0
  - sk-video=1.1.10=pyh24bf2e0_4
  - snappy=1.1.7=h777316e_3
  - sortedcontainers=2.1.0=py37_0
  - sqlite=3.31.1=he774522_0
  - tblib=1.6.0=py_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=hfa6e2cd_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py37he774522_0
  - tqdm=4.42.0=py_0
  - traitlets=4.3.3=py37_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py37_1
  - wheel=0.34.2=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - wincertstore=0.2=py37_0
  - winpty=0.4.3=4
  - xarray=0.12.3=py_0
  - xz=5.2.4=h2fa13f4_4
  - yaml=0.1.7=hc54c509_2
  - zarr=2.3.2=py37_0
  - zeromq=4.3.1=h33f27b4_3
  - zict=1.0.0=py_0
  - zipp=2.1.0=py_0
  - zlib=1.2.11=h62dcd97_3
  - zstd=1.3.7=h508b16e_0
  - pip:
    - chardet==3.0.4
    - idna==2.8
    - imageio==2.4.1
    - imageio-ffmpeg==0.3.0
    - pyte==0.8.0
    - requests==2.22.0
    - urllib3==1.25.3
    - win-unicode-console==0.5
prefix: C:\Users\wm228\Anaconda3\envs\ca_imaging
